export const LOAD_ALL_SHOWS_REQUEST = "LOAD_ALL_SHOWS_REQUEST";
export const LOAD_ALL_SHOWS_SUCCESS = "LOAD_ALL_SHOWS_SUCCESS";
export const LOAD_ALL_SHOWS_FAIL = "LOAD_ALL_SHOWS_FAIL";

export const GET_SHOW_DATA_REQUEST = "GET_SHOW_DATA_REQUEST";
export const GET_SHOW_DATA_SUCCESS = "GET_SHOW_DATA_SUCCESS";
export const GET_SHOW_DATA_FAIL = "GET_SHOW_DATA_FAIL";

export const GET_SEARCH_DATA_REQUEST = "GET_SEARCH_DATA_REQUEST";
export const GET_SEARCH_DATA_SUCCESS = "GET_SEARCH_DATA_SUCCESS";
export const GET_SEARCH_DATA_FAIL = "GET_SEARCH_DATA_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
